import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import Sidebar from "@/components/dashboard/sidebar/sideBar";
import Header from "@/components/dashboard/header/header";
import RegisterServiceWorker from "@/components/firebase/RegisterServiceWorker";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Nurse Lynx",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const userCookie = cookieStore.get("dataUser");
  const userData = userCookie?.value ? JSON.parse(userCookie.value) : null;
  const renderContent = () => (
    <div className="flex flex-row">
      <Sidebar userData={userData}/>
      <div className="flex-grow flex flex-col w-[75%]">
        <Header />
        <main className="flex-grow  text-black md:p-6 ml-0 md:ml-60 items-start h-screen">
          {children}
        </main>
      </div>
    </div>
  );

  return (
    <html lang="en" className={poppins.variable}>
      <body className="antialiased">
        {userData?.email ? renderContent() : children}
        <RegisterServiceWorker />
        <ToastContainer />
      </body>
    </html>
  );
}
